/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

// ATTENTION 
// This header was generated with ClassDumper on 10.5 but was edited  
// heavily to make it compile on both 10.5 and 10.6 development systems...

@class IKMipmapImage;

@interface IKImageCell : NSObject
{
    id _parent;
    id _cellSource;
    id _proxy;
    unsigned int _dataSourceIndex;
    unsigned int _mipmapDBIndex;
    IKMipmapImage *_mipmapImage;
    unsigned int _datasourceIsVectorial:1;
    float _alpha;
    NSMutableDictionary *_properties;
}

+ (id)_IKBuildImageWrapperForType:(id)fp8 withObject:(id)fp12 withOwner:(id)fp16;
- (id)init;
- (struct _NSRect)imageFrame;
- (void)invalidate;
- (void)validate;
- (void)mipmapImageChanged;
- (void)validateMipmapDBIndex;
- (id)mipmapDB;
- (unsigned int)mipmapDBIndex;
- (void)setCacheDBIndex:(unsigned int)fp8;
- (void)parentWillDie:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (void)setParent:(id)fp8;
- (id)parent;
- (void)setDataSource:(id)fp8;
- (id)dataSource;
- (unsigned int)dataSourceIndex;
- (void)setDataSourceIndex:(unsigned int)fp8;
- (id)mipmapImage;
- (void)setMipmapImage:(id)fp8;
- (float)alpha;
- (void)setAlpha:(float)fp8;
- (BOOL)isAnIcon;
- (BOOL)_representationTypeCanBePlayed:(id)fp8;
- (void)removeObjectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (void)checkMipmapVersion;
- (id)dataSourcePath;

@end

@interface IKImageBrowserCell : IKImageCell
{
    unsigned int _hidden:1;
    unsigned int _reordering:1;
    unsigned int _selected:1;
    NSRect _frame;
    NSRect _imageFrame;
    unsigned int _layoutValid:1;
    unsigned int _imageFrameValid:1;
    float _aspectRatio;
    unsigned int _aspectRatioValid:1;
    NSSize _titleSize;
    unsigned int _mipmapImageValid:1;
    unsigned int _imageValid:1;
    unsigned int _contentCanBePlayed:1;
    unsigned int _privateAnimationMask:1;
}

+ (void)stopCurrentPlayerIfAny;
+ (BOOL)aCellIsPlayingInView:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (void)invalidate;
- (void)validate;
- (id)originalImage;
- (id)sourceUID;
- (float)_aspectRatio;
- (float)aspectRatio;
- (void)setAspectRatio:(float)fp8;
- (int)heightOfInfoSpace;
- (BOOL)hasPreview;
- (NSRect)roundedFrame;
- (NSSize)imageSizeForCellSize:(NSSize)fp8 withAspectRatio:(float)fp16;
- (NSRect)imageFrameForCellFrame:(NSRect)fp8;
- (void)_computeImageFrame;
- (void)setPosition:(NSPoint)fp8;
- (void)setSize:(NSSize)fp8;
- (void)setFrame:(NSRect)fp8;
- (struct _NSPoint)position;
- (void)centerToPosition:(NSPoint)fp8;
- (NSRect)frame;
- (NSRect)imageFrame;
- (NSRect)imageBorderFrame;
- (BOOL)isLayoutValid;
- (void)setLayoutValid:(BOOL)fp8;
- (BOOL)hitTestWithPoint:(NSPoint)fp8;
- (BOOL)hitTestWithRect:(NSRect)fp8;
- (id)typeSelectString;
- (void)validateMipmapImage;
- (void)validateMipmapDBIndex;
- (void)validateImage;
- (void)reloadData;
- (void)prepareForImport;
- (void)didImport;
- (NSRect)_iconFrameForCellFrameSize:(NSSize)fp8;
- (NSSize)size;
- (BOOL)isSelected;
- (BOOL)isSelectable;
- (void)setSelected:(BOOL)fp8;
- (void)drawOverlays;
- (void)positionDidChange;
- (void)sizeDidChange;
- (void)willBeRemovedFromView;
- (BOOL)imageIsImported;
- (BOOL)needLoading;
- (BOOL)_preloadWithQuality:(int)fp8;
- (void)_preloadingEnded;
- (BOOL)preloadWithQuality:(int)fp8;
- (BOOL)preload;
- (id)bestMipmapForSize:(NSSize)fp8;
- (id)thumbnailImage;
- (void)mipmapImageChanged;
- (void)drawShadow;
- (void)drawImageOutline;
- (void)drawPlaceHolder;
- (void)drawBackground;
- (void)drawCenteredIcon:(id)fp8;
- (NSRect)playButtonFrame;
- (BOOL)_playerViewHasPlayControls;
- (void)drawPlayerControl;
- (void)drawImage:(id)fp8;
- (NSSize)_getTitleSize;
- (id)_currentTitleAttributes;
- (NSRect)titleFrame;
- (NSRect)titleStringFrame;
- (void)drawSelectionOnTitle;
- (void)drawTitleBackground;
- (void)drawTitle;
- (NSRect)subtitleFrame;
- (void)drawSubtitle;
- (NSRect)selectionFrame;
- (void)drawSelection;
- (void)drawDragHighlight;
- (void)draw;
- (void)freeOriginalImageCache;
- (void)freeVMCache;
- (void)freeExpendedRepresentationCaches;
- (BOOL)showPlayerControls;
- (id)playerView;
- (BOOL)contentCanBePlayed;
- (NSRect)playerFrame;
- (void)stopPlay;
- (void)startPlay;
- (BOOL)isPlaying;
- (id)browser;
- (void)setBrowser:(id)fp8;
- (BOOL)hidden;
- (void)setHidden:(BOOL)fp8;
- (BOOL)reordering;
- (void)setReordering:(BOOL)fp8;
- (unsigned int)privateAnimationMask;
- (void)setPrivateAnimationMask:(unsigned int)fp8;
- (BOOL)mouseDown:(NSPoint)fp8 inView:(id)fp16;
- (unsigned long long)fileSize;
- (void)installToolTips;

@end
